rules:
  - process_name:
      - aria2c
      - aria2c.exe
      - qbittorrent
      - qbittorrent.exe
      - qbittorrent-nox
      - Transmission
      - transmission-qt
      - transmission-qt.exe
      - transmission-daemon
      - BitComet
      - BitComet.exe
      - Thunder
      - Thunder.exe
      - Xunlei
      - Xunlei.exe
      - deluge
      - deluge.exe
      - deluged
      - Folx
      - fdm
      - fdm.exe
      - amule
      - amule.exe
      - emule
      - emule.exe
  - port:
      - 4662
      - 4672
      - 51413
  - port_range:
      - 6881:6889
  - domain_keyword:
      - tracker
      - announce
      - torrent
      - peer_id
